### ISSUE TITLE
Player vanishes on OSX after changing route 

### ISSUE THREAD

**Issue by greece57** [obraunsdorf/playbook-creator#6]
**BUG**
Player vanishes on OSX after changing route

**How to reconstruct**
I installed the app 
 - created a new playbook
 - create a new play (added Name, ShortName + "Spread Right")
 - moved slot to a "spread left" formation
 - selected for the left corner a 5+in
 - clicked "edit plays' categories" (which didn't work -> pop up with error -> pop up with save dialog)
 - selected for the left corner a corner
 => Player Vanishes

<img width="696" alt="Bildschirmfoto 2019-07-18 um 10 44 50" src="https://user-images.githubusercontent.com/9194851/61445649-14062100-a94e-11e9-96f5-71394e516901.png">

**Comment by obraunsdorf** [comment]
This bug is not specific to OSX.
It happens, if a route's endpoint is located outside the grid iron (Qt canvas).  This can happen e.g.,  if there is a route designed for a slot receiver assigned to a receiver aligned that is aligned more to the outside. 
For exmample the 5-Out route (which is one of the default routes): it goes strait up 5 yards and then 10 yards to the outside. If you assign it to some play which alignes less than 10 yards away from the outside, the route can not be drawn correctly.

**A proper fix** could be on every route assignment:
- for every path in the route:
  - sum up its x-coordinate with the sum of x-coordinates of the previous paths.[same with y-coordinates]
  - check if the sum is less than 0 or greater than PBCConfig.fieldwidth [same with fieldheight]
- print an error message and abort route assignment
